### ISSUE TITLE
Change the preview text

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/leaderboard#12]
The preview text of the website is the boilerplate text from Create React App. You can see this when the link is shared anywhere externally like on Discord or Whatsapp. It should be replaced with the something about the website

**Comment by mkamranhamid** [comment]
when sharing it on facebook it only shows the title because the other content is generated thru javascript in single page app.

**Comment by mkamranhamid** [comment]
We might need to use a server file to check if the request is coming from a crawler or browser and shows the result respectively. Are you up for it?

**Comment by RanjithGovindaraj** [comment]
Hey!! are these issues are created for the people participating in the contest? Can people outside your organization submit PR?

**Comment by srujandeshpande** [comment]
@mkamranhamid We're not looking to have any server files. The entire code should be static so it can be hosted on Github Pages

**Comment by srujandeshpande** [comment]
@RanjithGovindaraj Yes, these issues are mainly targeted to people participating in our contest. Although it looks like no one is working on this one, so you are free to contribute!

**Comment by mkamranhamid** [comment]
@srujandeshpande do you have ideas how we can do that without having a server file?

**Comment by RanjithGovindaraj** [comment]
@srujandeshpande thanks!! I will start working on it
