### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/leaderboard#14]
Open Source Projects should always have a LICENSE!
This tells people what they can and cannot do with the code availble in the public domain.

Most repositories should already have a license before you contribute, but this doesn't.

Go to Insights -> Commmunity -> License and choose the license.
This project should be licensed under the MIT License.

**Comment by Tegridy** [comment]
Hi, can i do this one ?

**Comment by Sheitak** [comment]
Hello, I can take care of this if you agree,

**Comment by RakshithRAcharya** [comment]
@srujandeshpande I will do this
