### ISSUE TITLE
Add an github profile picture next to the github username!

### ISSUE THREAD

**Issue by avinash-vk** [acmpesuecc/leaderboard#16]
Add an image next to the github profile link in the leader board stats.

Something similar to:
![image](https://user-images.githubusercontent.com/51489449/97103372-f89dd000-16d1-11eb-8feb-8e928811270e.png)

Make sure to take care of the responsiveness as well :)

**Comment by superneutrino8** [comment]
Hey @avinash-vk, Can I give this a try?
