### ISSUE TITLE
Add a Timer till the event end

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/leaderboard#17]
Add a timer above the Leaderboad table that shows the time left out in this event. (Days, Hours, Minutes, Seconds)
(Until 11:00 PM IST on 25th October 2020)

Bonus points for being aesthetically pleasing

**Comment by shreya-panale** [comment]
Hey @srujandeshpande ,I want to try it :)

**Comment by RakshithRAcharya** [comment]
Can I try this??
