### ISSUE TITLE
Fix color on blank search

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/leaderboard#24]
Upon searching for something and then deleting the searched text, all the results show up as searched (In the gray background color)
Ideally, none of them should when the field is empty

**Comment by chinmaym07** [comment]
Hey **@srujandeshpande**  Can I work on this issue. and please elaborate a little more on this.

**Comment by srujandeshpande** [comment]
Sure!

This is how the page looks in the beginning
![Screenshot from 2020-10-27 11-27-04](https://user-images.githubusercontent.com/47925600/97262700-6ae3f100-1847-11eb-9932-7d5df6988e5d.png)


This is how it looks when searching
![Screenshot from 2020-10-27 11-27-12](https://user-images.githubusercontent.com/47925600/97262702-6d464b00-1847-11eb-8bd3-8c86c4921138.png)


If you delete the search term, it looks like this when actually it should look like the first image
![Screenshot from 2020-10-27 11-27-14](https://user-images.githubusercontent.com/47925600/97262703-6e777800-1847-11eb-9af0-529fc87d2884.png)

**Comment by chinmaym07** [comment]
Hey **@srujandeshpande**  .I have raised #27 .Please Review.!
